version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    
  nsfw-api:
    build: .
    container_name: nsfw-api
    ports:
      - '8000:8000'
    environment:
      - NSFW_API_KEY=your-secure-key-here
      - CLOUD_PROVIDER=AWS
    depends_on:
      - redis
    
volumes:
  redis_data: